spring:
  application:
    name: cache-web-node
server:
  port: 7890



##分布式缓存redis配置
layering-cache:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    key-serializer: com.xul.core.redis.serializer.StringRedisSerializer
    value-serializer: com.xul.core.redis.serializer.ProtostuffRedisSerializer









